import type { DiagnosticIssue } from './types';

/**
 * Base de connaissances locale — pannes moteur courantes.
 * Données indicatives (ordres de grandeur) pour le moteur de diagnostic Sprint 3.1.
 */
export const KNOWLEDGE_BASE: readonly DiagnosticIssue[] = [
  {
    id: 'engine_knocking',
    nom: 'Cognement moteur (knocking)',
    categorie: 'engine',
    description: 'Détonation ou cognement à l\'accélération ou sous charge, souvent lié à l\'allumage, à la suralimentation ou à un mauvais carburant.',
    symptomesAudio: [
      'Claquements métalliques rythmés à l\'accélération',
      'Bruit sec sous charge à bas ou moyen régime',
      'Intensité qui augmente avec la charge moteur',
    ],
    niveauGravite: 5,
    niveauUrgence: 'critical',
    confianceParDefaut: 0.82,
    coutMoyenMin: 400,
    coutMoyenMax: 2500,
    tempsReparationMoyenHeures: 6,
    peutContinuerARouler: false,
    conseils: [
      'Réduisez immédiatement la charge moteur et évitez les accélérations franches.',
      'Arrêtez le véhicule si le bruit s\'intensifie ou si le voyant moteur clignote.',
      'Faites contrôler l\'allumage, la suralimentation et la qualité du carburant.',
    ],
  },
  {
    id: 'timing_chain_noise',
    nom: 'Bruit de chaîne de distribution',
    categorie: 'distribution',
    description: 'Usure ou tension insuffisante de la chaîne/courroie de distribution provoquant un cliquetis au ralenti ou au démarrage.',
    symptomesAudio: [
      'Cliquetis métallique au ralenti, surtout à froid',
      'Bruit qui disparaît ou diminue une fois le moteur chaud',
      'Grincement léger à l\'accélération légère',
    ],
    niveauGravite: 4,
    niveauUrgence: 'high',
    confianceParDefaut: 0.78,
    coutMoyenMin: 600,
    coutMoyenMax: 1800,
    tempsReparationMoyenHeures: 8,
    peutContinuerARouler: false,
    conseils: [
      'Évitez les régimes moteur élevés jusqu\'à diagnostic garage.',
      'Surveillez l\'apparition de voyants moteur ou de ratés.',
      'Planifiez une inspection de la tension de distribution rapidement.',
    ],
  },
  {
    id: 'turbo_issue',
    nom: 'Anomalie turbo',
    categorie: 'turbo',
    description: 'Usure ou fuite du turbocompresseur entraînant sifflement anormal, perte de puissance ou fumée d\'échappement.',
    symptomesAudio: [
      'Sifflement aigu à l\'accélération',
      'Bruit de roulement ou de grésillement côté turbo',
      'Perte de souffle accompagnée d\'un bruit d\'air',
    ],
    niveauGravite: 4,
    niveauUrgence: 'high',
    confianceParDefaut: 0.8,
    coutMoyenMin: 800,
    coutMoyenMax: 3500,
    tempsReparationMoyenHeures: 10,
    peutContinuerARouler: false,
    conseils: [
      'Ne forcez pas le turbo : accélérez progressivement.',
      'Vérifiez le niveau d\'huile moteur (consommation anormale possible).',
      'Faites contrôler les durites, l\'intercooler et le jeu du turbocompresseur.',
    ],
  },
  {
    id: 'injector_noise',
    nom: 'Bruit d\'injecteurs',
    categorie: 'injection',
    description: 'Injecteurs encrassés ou défaillants produisant un cliquetis diesel anormal ou un ralenti irrégulier.',
    symptomesAudio: [
      'Cliquetis rapide et régulier au ralenti (diesel)',
      'Ralenti instable avec à-coups sonores',
      'Bruit d\'injection plus fort qu\'à l\'habitude',
    ],
    niveauGravite: 3,
    niveauUrgence: 'medium',
    confianceParDefaut: 0.71,
    coutMoyenMin: 150,
    coutMoyenMax: 900,
    tempsReparationMoyenHeures: 3,
    peutContinuerARouler: true,
    conseils: [
      'Un additif carburant adapté peut aider en cas d\'encrassement léger.',
      'Surveillez la consommation et les fumées à l\'échappement.',
      'Faites tester les injecteurs si le ralenti reste irrégulier.',
    ],
  },
  {
    id: 'idle_instability',
    nom: 'Instabilité au ralenti',
    categorie: 'engine',
    description: 'Régime moteur instable au ralenti, souvent lié à un capteur, un calage ou un mélange air/carburant incorrect.',
    symptomesAudio: [
      'Ralenti qui monte et descend de façon audible',
      'Vibrations et à-coups au repos',
      'Moteur qui peine à rester au ralenti',
    ],
    niveauGravite: 2,
    niveauUrgence: 'medium',
    confianceParDefaut: 0.65,
    coutMoyenMin: 80,
    coutMoyenMax: 450,
    tempsReparationMoyenHeures: 2,
    peutContinuerARouler: true,
    conseils: [
      'Notez si le problème apparaît à froid, à chaud ou les deux.',
      'Vérifiez l\'absence de voyant moteur allumé.',
      'Faites lire les défauts OBD si l\'instabilité persiste plus de quelques jours.',
    ],
  },
  {
    id: 'exhaust_leak',
    nom: 'Fuite d\'échappement',
    categorie: 'exhaust',
    description: 'Joint ou ligne d\'échappement percée provoquant un bruit de pot d\'échappement anormal et une perte de performance.',
    symptomesAudio: [
      'Petarades ou souffle d\'air sous le plancher',
      'Bruit d\'échappement plus fort qu\'à l\'habitude',
      'Sifflement ou chuintement à l\'accélération',
    ],
    niveauGravite: 3,
    niveauUrgence: 'medium',
    confianceParDefaut: 0.74,
    coutMoyenMin: 100,
    coutMoyenMax: 600,
    tempsReparationMoyenHeures: 2.5,
    peutContinuerARouler: true,
    conseils: [
      'Évitez les trajets longs si l\'odeur de gaz d\'échappement pénètre l\'habitacle.',
      'Inspectez visuellement les joints et la ligne sous le véhicule.',
      'Faites réparer rapidement pour limiter la corrosion et les émissions.',
    ],
  },
  {
    id: 'water_pump_bearing',
    nom: 'Roulement de pompe à eau',
    categorie: 'cooling',
    description: 'Usure du roulement de la pompe à eau produisant un grincement ou un sifflement côté courroie accessoires.',
    symptomesAudio: [
      'Grincement continu à froid qui peut s\'atténuer à chaud',
      'Bruit de roulement côté avant du moteur',
      'Sifflement modulé avec le régime moteur',
    ],
    niveauGravite: 3,
    niveauUrgence: 'high',
    confianceParDefaut: 0.7,
    coutMoyenMin: 200,
    coutMoyenMax: 700,
    tempsReparationMoyenHeures: 4,
    peutContinuerARouler: false,
    conseils: [
      'Surveillez la température moteur et le niveau de liquide de refroidissement.',
      'Évitez les longs trajets si le bruit s\'accentue.',
      'Remplacez la pompe à eau avant une rupture de courroie ou une surchauffe.',
    ],
  },
  {
    id: 'alternator_bearing',
    nom: 'Roulement d\'alternateur',
    categorie: 'electrical',
    description: 'Roulement d\'alternateur usé générant un grincement aigu ou un sifflement sous le capot, indépendant de la charge moteur.',
    symptomesAudio: [
      'Grincement aigu constant au ralenti',
      'Bruit qui augmente légèrement avec le régime',
      'Parfois accompagné de voyant batterie faible',
    ],
    niveauGravite: 3,
    niveauUrgence: 'medium',
    confianceParDefaut: 0.68,
    coutMoyenMin: 250,
    coutMoyenMax: 650,
    tempsReparationMoyenHeures: 2,
    peutContinuerARouler: true,
    conseils: [
      'Limitez les accessoires électriques (clim, chauffage siège) si le voyant batterie s\'allume.',
      'Faites tester la charge alternateur et l\'état du roulement.',
      'Prévoyez le remplacement avant une panne complète de charge.',
    ],
  },
  {
    id: 'belt_slip',
    nom: 'Patinnage de courroie accessoires',
    categorie: 'belt',
    description: 'Courroie accessoires usée ou mal tendue provoquant un crissement à l\'accélération ou au démarrage.',
    symptomesAudio: [
      'Crissement bref à l\'accélération ou au démarrage',
      'Bruit de frottement sous le capot à froid',
      'Grincement qui disparaît une fois la courroie chaude',
    ],
    niveauGravite: 2,
    niveauUrgence: 'medium',
    confianceParDefaut: 0.72,
    coutMoyenMin: 60,
    coutMoyenMax: 250,
    tempsReparationMoyenHeures: 1,
    peutContinuerARouler: true,
    conseils: [
      'Évitez de forcer le moteur à froid si le crissement persiste.',
      'Inspectez l\'état et la tension de la courroie accessoires.',
      'Remplacez courroie et galets si le patinage est récurrent.',
    ],
  },
  {
    id: 'misfire',
    nom: 'Raté d\'allumage (misfire)',
    categorie: 'engine',
    description: 'Une ou plusieurs cylindres ne combustent pas correctement, provoquant un ralenti rugueux et des à-coups.',
    symptomesAudio: [
      'Ralenti rugueux type « toux » moteur',
      'À-coups réguliers à bas régime',
      'Bruit de combustion irrégulier',
    ],
    niveauGravite: 4,
    niveauUrgence: 'high',
    confianceParDefaut: 0.76,
    coutMoyenMin: 120,
    coutMoyenMax: 800,
    tempsReparationMoyenHeures: 3,
    peutContinuerARouler: false,
    conseils: [
      'Ne roulez pas longtemps avec un voyant moteur clignotant.',
      'Faites lire les codes défaut pour identifier le cylindre concerné.',
      'Vérifiez bougies, bobines et injecteurs selon le diagnostic OBD.',
    ],
  },
  {
    id: 'wheel_bearing',
    nom: 'Roulement de roue avant',
    categorie: 'suspension',
    description: 'Usure du roulement de roue produisant un grondement modulé avec la vitesse, distinct du bruit moteur au ralenti.',
    symptomesAudio: [
      'Grondement croissant avec la vitesse du véhicule',
      'Bruit qui change en virage (charge sur une roue)',
      'Peu ou pas de bruit au ralenti moteur seul',
    ],
    niveauGravite: 3,
    niveauUrgence: 'medium',
    confianceParDefaut: 0.69,
    coutMoyenMin: 180,
    coutMoyenMax: 450,
    tempsReparationMoyenHeures: 2,
    peutContinuerARouler: true,
    conseils: [
      'Identifiez si le bruit disparaît au ralenti immobile (suspicion roulement).',
      'Faites contrôler le jeu du roulement au garage.',
      'Remplacez avant usure excessive pouvant endommager la fusée.',
    ],
  },
  {
    id: 'valve_tick',
    nom: 'Jeu aux soupapes (ticking)',
    categorie: 'engine',
    description: 'Jeu aux soupapes excessif ou huile insuffisante au démarrage provoquant un tic-tac régulier en tête de culasse.',
    symptomesAudio: [
      'Tic-tac régulier et métallique en tête de culasse',
      'Bruit souvent plus marqué à froid',
      'Peut diminuer après montée en température',
    ],
    niveauGravite: 2,
    niveauUrgence: 'low',
    confianceParDefaut: 0.66,
    coutMoyenMin: 100,
    coutMoyenMax: 500,
    tempsReparationMoyenHeures: 4,
    peutContinuerARouler: true,
    conseils: [
      'Vérifiez le niveau et la viscosité d\'huile moteur.',
      'Si le bruit persiste à chaud, faites régler le jeu aux soupapes.',
      'Surveillez l\'apparition de pertes de performance.',
    ],
  },
  {
    id: 'intake_leak',
    nom: 'Fuite d\'admission d\'air',
    categorie: 'intake',
    description: 'Entrée d\'air parasite en amont du débitmètre provoquant sifflement, ralenti instable et perte de puissance.',
    symptomesAudio: [
      'Sifflement ou aspiration anormale au ralenti',
      'Bruit d\'air sous le capot à l\'accélération légère',
      'Ralenti instable avec bruit de « succion »',
    ],
    niveauGravite: 3,
    niveauUrgence: 'medium',
    confianceParDefaut: 0.73,
    coutMoyenMin: 50,
    coutMoyenMax: 350,
    tempsReparationMoyenHeures: 1.5,
    peutContinuerARouler: true,
    conseils: [
      'Inspectez durites d\'admission, colliers et joints spi.',
      'Un test de fumée au garage confirme rapidement une fuite.',
      'Corrigez tôt pour éviter un mélange pauvre et surconsommation.',
    ],
  },
  {
    id: 'catalytic_converter',
    nom: 'Pot catalytique obstrué',
    categorie: 'exhaust',
    description: 'Catalyseur encrassé ou effondré limitant l\'échappement et provoquant un souffle étouffé et une perte de puissance.',
    symptomesAudio: [
      'Souffle étouffé à l\'échappement',
      'Bruit de cliquetis interne au pot catalytique',
      'Difficulté à monter en régime avec bruit d\'échappement chargé',
    ],
    niveauGravite: 4,
    niveauUrgence: 'high',
    confianceParDefaut: 0.75,
    coutMoyenMin: 400,
    coutMoyenMax: 1500,
    tempsReparationMoyenHeures: 3,
    peutContinuerARouler: false,
    conseils: [
      'Évitez les trajets longs si la perte de puissance est importante.',
      'Faites mesurer la contre-pression d\'échappement.',
      'Identifiez la cause racine (ratés, surconsommation huile) avant remplacement.',
    ],
  },
  {
    id: 'normal_engine',
    nom: 'Moteur sain',
    categorie: 'other',
    description: 'Signature acoustique dans les normes pour un moteur au ralenti — aucune anomalie significative détectée.',
    symptomesAudio: [
      'Ralenti régulier sans claquement ni sifflement anormal',
      'Absence de grondement modulé avec la vitesse au repos',
      'Niveau sonore cohérent avec un moteur entretenu',
    ],
    niveauGravite: 1,
    niveauUrgence: 'low',
    confianceParDefaut: 0.94,
    coutMoyenMin: 0,
    coutMoyenMax: 0,
    tempsReparationMoyenHeures: 0,
    peutContinuerARouler: true,
    conseils: [
      'Poursuivez l\'entretien périodique prévu par le constructeur.',
      'Refaites un contrôle acoustique si de nouveaux bruits apparaissent.',
      'Conservez ce enregistrement comme référence pour comparaison future.',
    ],
  },
] as const;

const issueIndex = new Map<string, DiagnosticIssue>(
  KNOWLEDGE_BASE.map((issue) => [issue.id, issue])
);

export function getIssueById(id: string): DiagnosticIssue | undefined {
  return issueIndex.get(id);
}

export function getAllIssues(): DiagnosticIssue[] {
  return [...KNOWLEDGE_BASE];
}
